### PR TITLE
Issue 9

### LINKED ISSUE #9: Failed to parse negative int

### PR DESCRIPTION
**Pull request by harryzcy**
Fixes #9

### CODE REVIEW

File: src/evaluator.rs [hunk 1]
```diff
@@ -5,7 +5,7 @@ use std::process::exit;
 
 #[derive(Debug)]
 pub enum LimpValue {
-	Integer(u64),
```
Comment (eric-unc) [inline src/evaluator.rs:8]: oh lol, this is pretty dumb on my part 😢

Comment (harryzcy) [reply src/evaluator.rs:8]: it's a tiny issue
